version: '3'
services:
  api-gateway:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - booking
      - listing
      - user
    env_file: .env


  auth:
    build: ./apps/auth
    ports:
      - '3001:3001'
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
    env_file: .env
    expose:
      - '3001'


  booking:
    build: ./apps/booking
    ports:
      - '3005:3005'
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
    env_file: .env
    expose:
      - '3005'


  listing:
    build: ./apps/listing
    ports:
      - '3004:3004'
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
    env_file: .env
    expose:
      - '3004'


  user:
    build: ./apps/user
    ports:
      - '3002:3002'
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./shared:/app/shared
    env_file: .env
    expose:
      - '3002'
